### ISSUE TITLE
Images need alt text

### ISSUE THREAD

**Issue by emberborja** [WillBridge0789/ComicCraze-frontend#10]
It is best for accessibility and general user experience if you provide real text in the alt attribute of img elements instead of what appears to be the copy and pasted default from the bootstrap documentation. (alt="...") If an image is unimportant for the content of a page then the alt attribute should be an empty string.

Here is the pertinent documentation -> https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attributes

**Comment by WillBridge0789** [comment]
Added alts to images
