### ISSUE TITLE
Create Issues and Project board

### ISSUE THREAD

**Issue by emberborja** [WillBridge0789/ComicCraze-frontend#4]
I would really like to contribute to your project but there are no open issues or public project board. These two feature in Github help others to understand what work you would like done first and what direction you are hoping to move with your project.

**Comment by WillBridge0789** [comment]
OH ok. I'm sorry. I'll try to change that. I had a project board I believe still on there. I'll see if I can make both that and the project itself public so that way it can allow notes and edits.

**Comment by emberborja** [comment]
Project board created and issues made
