### ISSUE TITLE
Comic Craze Favicon

### ISSUE THREAD

**Issue by emberborja** [WillBridge0789/ComicCraze-frontend#5]
It would be nice to turn the CC logo into a favicon so that you can have it display on the web tab instead of the react favicon.

**Comment by WillBridge0789** [comment]
I'll look it up and see how to do that. I've never actually changed the favicon before. Thank you for the idea. I'll definitely do that 😃

**Comment by WillBridge0789** [comment]
Changed favicon to the Comic Craze C's
